### ISSUE TITLE
Move copyFile from dev-bundler-rollup here

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-utils#18]
It's a too generic util to be kept there.

**Comment by Reinmar** [comment]
And I need this util in ckeditor5.

**Comment by Reinmar** [comment]
I added the function in 4477781. It needs a test now.

**Comment by pomek** [comment]
At this moment `copyFile` doesn't handle errors. @Reinmar and I considered how to create proper tests and how to handles errors.

Unfortunately, testing stream isn't easy task, so I will rewrite the function using a native node [file system](https://nodejs.org/api/fs.html) with [steroids (_fs-extra_)](https://www.npmjs.com/package/fs-extra).
