### ISSUE TITLE
Create a util like runSequence but which accepts functions, not gulp tasks

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-utils#21]
In order to combine multiple task-like functions into one bigger task, we use [`runSequence`](https://github.com/OverZealous/run-sequence). Unfortunately, it works only with gulp task, so you need to define every component task, which bloats gulpfiles. E.g. in CKEditor 5 we've got now [a lot of useless tasks](https://github.com/ckeditor/ckeditor5/blob/772d2b68e868024a0ad2c8cc956c3c3605496757/gulpfile.js) there, while this gulpfile should be minimal because many other projects, while integrating CKEditor, will have to define those tasks.

So what we need, is an ability to take a list of functions, which normally would be passed to gulp, and run them in sequence. Just like `runSequence` would do with gulp tasks.

Example:

``` js
function taskA() {
    return somePromise;
}

function taskB() {
    return someStream;
}

function taskC() {
    // returns nothing - synchronous
}

gulp.task( 'masterTask', () => runSequence( taskA, taskB, taskC ) );
```

This will:
- run taskA
- then once that promise is resolved, run taskB
- then when that stream has finished, run taskC

Note: Gulp 4 will introduce anonymous tasks, which seems as a partial solution to our problem. Partial, because those anonymous tasks are logged onto the console as something like "Running <anonyoums task>", which I'd like to avoid. Also, I have a feeling that such a function should already exist, but I can't find it... ;/

**Comment by Reinmar** [comment]
Related issue https://github.com/ckeditor/ckeditor5/issues/308.

**Comment by Reinmar** [comment]
BTW. Our `runSequence` could return a promise for simplicity. The original one has a callback, which I don't really like.

**Comment by Reinmar** [comment]
BTW2. Original `runSequence` allows running things in parallel. This is a secondary feature for us. First, we need to be able to sequence things. But if the implementation will promisify every step, then running things in parallel will be easy to achieve too.

**Comment by Reinmar** [comment]
There are two things which may help us:

1. https://github.com/robrich/orchestrator – gulp uses it internally and if gulp 4 will still rely on it (cause the project looks a bit dead now) we could perhaps use it internally in our runSeq function.
2. https://gist.github.com/wookieb/a549956a037b85cc973ebd9f5f22df12 – we may use this simple wrapper on gulp. However, it creates anonymous gulp tasks in order to run all those functions, so that's a bit of a bad smell.

**Comment by Reinmar** [comment]
Success! Gulp 4 is using https://www.npmjs.com/package/undertaker which is exactly what we need. So perhaps we don't even need any custom util – it should be convenient enough to use Undertaker.

**Comment by pomek** [comment]
Undertaker will resolve our problem. I used it in [`compiler`](https://github.com/ckeditor/ckeditor5-dev-compiler/blob/55a364fba5248ad9205d9f64ef66c26300bdd1a1/lib/compiler/index.js#L317-L326) and it works pretty well.

**Comment by Reinmar** [comment]
And a related thread in the undertaker's issue tracker: https://github.com/gulpjs/undertaker/issues/67. We're checking whether we're actually using it correctly.

**Comment by pomek** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-dev/issues/36.
