### ISSUE TITLE
Remove condition form `stream#isTestFile`

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5-dev-utils#22]
Related to: https://github.com/ckeditor/ckeditor5-engine/issues/610.

Condition `dirFrag != '_utils-tests'` in function `isTestFile` is not needed after changes made in the issue above.

**Comment by Reinmar** [comment]
There may be other `_utils-tests` directories. As I explained in https://github.com/ckeditor/ckeditor5/issues/333#issuecomment-248857318 there are dev utils and test utils.

**Comment by maxbarnas** [comment]
Thanks for clarifying. Wasn't sure about this - that's why I didn't labeled it as "confirmed". :)
