### ISSUE TITLE
Postpone require() calls to improve performance

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-utils#3]
Like in 2nd point in https://github.com/ckeditor/ckeditor5/issues/170

**Comment by maxbarnas** [comment]
I did quick benchmark and these are the results:
#### Before:
```gulp something  0.62s user 0.09s system 102% cpu 0.684 total```
#### After:
```gulp something  0.22s user 0.04s system 101% cpu 0.263 total```
