### ISSUE TITLE
parseRepositoryUrl doesn't match tag branches

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-utils#36]
It fails on:

```
"ckeditor5-autoformat": "ckeditor/ckeditor5-autoformat#v0.3.0"
```

I'm not sure where the regexp comes from, but it's definitely very strict. Isn't there another method to parse this? Like a standard URL parser?

**Comment by pomek** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-dev/issues/35.
