### ISSUE TITLE
Review dependencies

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-utils#5]
It seems that some of these package deps are not needed. E.g. `git-guppy` isn't used anywhere.

**Comment by Reinmar** [comment]
<img width="1069" alt="screen shot 2016-07-25 at 21 46 02" src="https://cloud.githubusercontent.com/assets/156149/17114898/3a8c4bfc-52b1-11e6-959d-ba9e06e3edbc.png">

**Comment by Reinmar** [comment]
When cleaning up deps I stumbled upon an issue with JSHint. Turns out it needs to be installed in every package using `ckeditor5-dev-lint`. See: https://github.com/spalger/gulp-jshint/issues/145 and https://codingwithspike.wordpress.com/2016/01/21/dealing-with-the-deprecation-of-peerdependencies-in-npm-3/.

**Comment by maxbarnas** [comment]
How to replicate the problem you found about JSHint?

**Comment by Reinmar** [comment]
There's no point in replicating (it'd require making sure that jshint is not installed by some other package for some reason), because the gulp-jshint docs say that jshint must be installed.

**Comment by Reinmar** [comment]
But if you want to see it live, then try to use `gulp lint` in this package when jshint isn't installed. It failed for me.

**Comment by Reinmar** [comment]
OK, this is weird. I'm sure it didn't work yesterday, because I reproduced it more than once. But it works now, because ckeditor5-dev-lint installs jshint inside itself, so it seems that yesterday I did something differently.

Anyway, I removed jshint from this package.json in https://github.com/ckeditor/ckeditor5-dev-utils/commit/fc69ae8178a23c09434037cd257b26ee6aeef93d.
