### ISSUE TITLE
Move builder utils to ckeditor5-dev-builder

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-utils#8]
`lib/build.js` contains utils which are very related to building CKEditor, so it's better if they are in the ckeditor5-dev-builder package.

However, they should be reviewed first, because functions like https://github.com/ckeditor/ckeditor5-dev-utils/blob/master/lib/build.js#L52 makes for perfect generic utils and should be kept here.

**Comment by pomek** [comment]
I have a feeling that this issue can be connected with https://github.com/ckeditor/ckeditor5-dev-builder/pull/4.
